package com.androidint.todo.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)


//Light Theme:
val LightPrimary = Color(0xFF6200EE)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFFFFF)
val LightOnPrimaryContainer = Color(0xFF6200EE)
val LightInversePrimary = Color(0xFF6200EE)
val LightSecondary = Color(0xFF03DAC6)
val LightOnSecondary = Color(0xFF000000)
val LightSecondaryContainer = Color(0xFFFFFFFF)
val LightOnSecondaryContainer = Color(0xFF03DAC6)
val LightTertiary = Color(0xFFBB86FC)
val LightOnTertiary = Color(0xFF000000)
val LightTertiaryContainer = Color(0xFFFFFFFF)
val LightOnTertiaryContainer = Color(0xFFBB86FC)
val LightBackground = Color(0xFFFFFFFF)
val LightOnBackground = Color(0xFF000000)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF000000)
val LightSurfaceVariant = Color(0xFFE0E0E0)
val LightOnSurfaceVariant = Color(0xFF000000)
val LightInverseSurface = Color(0xFF121212)
val LightInverseOnSurface = Color(0xFFFFFFFF)
val LightOutline = Color(0xFF000000)


//Dark Theme:
val DarkPrimary = Color(0xFFBB86FC)
val DarkOnPrimary = Color(0xFFFFFFFF)
val DarkPrimaryContainer = Color(0xFF333333)
val DarkOnPrimaryContainer = Color(0xFFBB86FC)
val DarkInversePrimary = Color(0xFFBB86FC)
val DarkSecondary = Color(0xFF03DAC6)
val DarkOnSecondary = Color(0xFF000000)
val DarkSecondaryContainer = Color(0xFF333333)
val DarkOnSecondaryContainer = Color(0xFF03DAC6)
val DarkTertiary = Color(0xFF6200EE)
val DarkOnTertiary = Color(0xFFFFFFFF)
val DarkTertiaryContainer = Color(0xFF333333)
val DarkOnTertiaryContainer = Color(0xFF6200EE)
val DarkBackground = Color(0xFF121212)
val DarkOnBackground = Color(0xFFFFFFFF)
val DarkSurface = Color(0xFF333333)
val DarkOnSurface = Color(0xFFFFFFFF)
val DarkSurfaceVariant = Color(0xFF444444)
val DarkOnSurfaceVariant = Color(0xFFFFFFFF)
val DarkInverseSurface = Color(0xFFFFFFFF)
val DarkInverseOnSurface = Color(0xFF000000)
val DarkOutline = Color(0xFFFFFFFF)

//High Contrast Light Theme:
val HighContrastLightPrimary = Color(0xFF6200EE)
val HighContrastLightOnPrimary = Color(0xFFFFFFFF)
val HighContrastLightPrimaryContainer = Color(0xFFFFFFFF)
val HighContrastLightOnPrimaryContainer = Color(0xFF6200EE)
val HighContrastLightInversePrimary = Color(0xFF6200EE)
val HighContrastLightSecondary = Color(0xFF03DAC6)
val HighContrastLightOnSecondary = Color(0xFF000000)
val HighContrastLightSecondaryContainer = Color(0xFFFFFFFF)
val HighContrastLightOnSecondaryContainer = Color(0xFF03DAC6)
val HighContrastLightTertiary = Color(0xFFBB86FC)
val HighContrastLightOnTertiary = Color(0xFF000000)
val HighContrastLightTertiaryContainer = Color(0xFFFFFFFF)
val HighContrastLightOnTertiaryContainer = Color(0xFFBB86FC)
val HighContrastLightBackground = Color(0xFFFFFFFF)
val HighContrastLightOnBackground = Color(0xFF000000)
val HighContrastLightSurface = Color(0xFFFFFFFF)
val HighContrastLightOnSurface = Color(0xFF000000)
val HighContrastLightSurfaceVariant = Color(0xFFE0E0E0)
val HighContrastLightOnSurfaceVariant = Color(0xFF000000)
val HighContrastLightInverseSurface = Color(0xFF121212)
val HighContrastLightInverseOnSurface = Color(0xFFFFFFFF)
val HighContrastLightOutline = Color(0xFF000000)

//High Contrast Dark Theme:
val HighContrastDarkPrimary = Color(0xFFBB86FC)
val HighContrastDarkOnPrimary = Color(0xFFFFFFFF)
val HighContrastDarkPrimaryContainer = Color(0xFF333333)
val HighContrastDarkOnPrimaryContainer = Color(0xFFBB86FC)
val HighContrastDarkInversePrimary = Color(0xFFBB86FC)
val HighContrastDarkSecondary = Color(0xFF03DAC6)
val HighContrastDarkOnSecondary = Color(0xFF000000)
val HighContrastDarkSecondaryContainer = Color(0xFF333333)
val HighContrastDarkOnSecondaryContainer = Color(0xFF03DAC6)
val HighContrastDarkTertiary = Color(0xFF6200EE)
val HighContrastDarkOnTertiary = Color(0xFFFFFFFF)
val HighContrastDarkTertiaryContainer = Color(0xFF333333)
val HighContrastDarkOnTertiaryContainer = Color(0xFF6200EE)
val HighContrastDarkBackground = Color(0xFF121212)
val HighContrastDarkOnBackground = Color(0xFFFFFFFF)
val HighContrastDarkSurface = Color(0xFF333333)
val HighContrastDarkOnSurface = Color(0xFFFFFFFF)
val HighContrastDarkSurfaceVariant = Color(0xFF444444)
val HighContrastDarkOnSurfaceVariant = Color(0xFFFFFFFF)
val HighContrastDarkInverseSurface = Color(0xFFFFFFFF)
val HighContrastDarkInverseOnSurface = Color(0xFF000000)
val HighContrastDarkOutline = Color(0xFFFFFFFF)